# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from uart_process_2/uart_receive.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class uart_receive(genpy.Message):
  _md5sum = "9eb1c17f9d76fdce5a06ed519a258d0d"
  _type = "uart_process_2/uart_receive"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 yaw
float32 pitch
uint8 mod
uint8 red_blue
uint8 shoot_speed_mod"""
  __slots__ = ['yaw','pitch','mod','red_blue','shoot_speed_mod']
  _slot_types = ['float32','float32','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       yaw,pitch,mod,red_blue,shoot_speed_mod

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(uart_receive, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.yaw is None:
        self.yaw = 0.
      if self.pitch is None:
        self.pitch = 0.
      if self.mod is None:
        self.mod = 0
      if self.red_blue is None:
        self.red_blue = 0
      if self.shoot_speed_mod is None:
        self.shoot_speed_mod = 0
    else:
      self.yaw = 0.
      self.pitch = 0.
      self.mod = 0
      self.red_blue = 0
      self.shoot_speed_mod = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2f3B().pack(_x.yaw, _x.pitch, _x.mod, _x.red_blue, _x.shoot_speed_mod))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 11
      (_x.yaw, _x.pitch, _x.mod, _x.red_blue, _x.shoot_speed_mod,) = _get_struct_2f3B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2f3B().pack(_x.yaw, _x.pitch, _x.mod, _x.red_blue, _x.shoot_speed_mod))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 11
      (_x.yaw, _x.pitch, _x.mod, _x.red_blue, _x.shoot_speed_mod,) = _get_struct_2f3B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2f3B = None
def _get_struct_2f3B():
    global _struct_2f3B
    if _struct_2f3B is None:
        _struct_2f3B = struct.Struct("<2f3B")
    return _struct_2f3B
