// Generated by gencpp from file sagitari_debug/sagitari_img_debug.msg
// DO NOT EDIT!


#ifndef SAGITARI_DEBUG_MESSAGE_SAGITARI_IMG_DEBUG_H
#define SAGITARI_DEBUG_MESSAGE_SAGITARI_IMG_DEBUG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace sagitari_debug
{
template <class ContainerAllocator>
struct sagitari_img_debug_
{
  typedef sagitari_img_debug_<ContainerAllocator> Type;

  sagitari_img_debug_()
    : title()
    , image()  {
    }
  sagitari_img_debug_(const ContainerAllocator& _alloc)
    : title(_alloc)
    , image(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _title_type;
  _title_type title;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_type;
  _image_type image;





  typedef boost::shared_ptr< ::sagitari_debug::sagitari_img_debug_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sagitari_debug::sagitari_img_debug_<ContainerAllocator> const> ConstPtr;

}; // struct sagitari_img_debug_

typedef ::sagitari_debug::sagitari_img_debug_<std::allocator<void> > sagitari_img_debug;

typedef boost::shared_ptr< ::sagitari_debug::sagitari_img_debug > sagitari_img_debugPtr;
typedef boost::shared_ptr< ::sagitari_debug::sagitari_img_debug const> sagitari_img_debugConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sagitari_debug::sagitari_img_debug_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sagitari_debug::sagitari_img_debug_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sagitari_debug::sagitari_img_debug_<ContainerAllocator1> & lhs, const ::sagitari_debug::sagitari_img_debug_<ContainerAllocator2> & rhs)
{
  return lhs.title == rhs.title &&
    lhs.image == rhs.image;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sagitari_debug::sagitari_img_debug_<ContainerAllocator1> & lhs, const ::sagitari_debug::sagitari_img_debug_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sagitari_debug

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sagitari_debug::sagitari_img_debug_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sagitari_debug::sagitari_img_debug_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sagitari_debug::sagitari_img_debug_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sagitari_debug::sagitari_img_debug_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sagitari_debug::sagitari_img_debug_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sagitari_debug::sagitari_img_debug_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sagitari_debug::sagitari_img_debug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c762dcea1190e889820cef1cb4eeff24";
  }

  static const char* value(const ::sagitari_debug::sagitari_img_debug_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc762dcea1190e889ULL;
  static const uint64_t static_value2 = 0x820cef1cb4eeff24ULL;
};

template<class ContainerAllocator>
struct DataType< ::sagitari_debug::sagitari_img_debug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sagitari_debug/sagitari_img_debug";
  }

  static const char* value(const ::sagitari_debug::sagitari_img_debug_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sagitari_debug::sagitari_img_debug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string title\n"
"sensor_msgs/Image image\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::sagitari_debug::sagitari_img_debug_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sagitari_debug::sagitari_img_debug_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.title);
      stream.next(m.image);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sagitari_img_debug_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sagitari_debug::sagitari_img_debug_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sagitari_debug::sagitari_img_debug_<ContainerAllocator>& v)
  {
    s << indent << "title: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.title);
    s << indent << "image: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SAGITARI_DEBUG_MESSAGE_SAGITARI_IMG_DEBUG_H
